FROM python:3.11-slim

WORKDIR /app

# Install dependensi sistem (dibutuhkan oleh asyncpg & GeoAlchemy2)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

EXPOSE 8000
